### ISSUE TITLE
Build errors on Windows

### ISSUE THREAD

**Issue by oviano** [spc476/SPCDNS#10]
Hello

Firstly, thank you for the library, it's perfect.

This line doesn't compile with MSVC however, in C++ mode:

char   buffer[newlen + 1];

This is because VLAs are not supported.

It's trivial to replace with malloc/free, but that would violate your "this library doesn't allocate memory" strategy....other alternative is to declare it as size UINT16_MAX * 2, but that seems excessive.

**Comment by spc476** [comment]
Hopefully, I removed all the VLAs from the codebase.
