### ISSUE TITLE
Using non-default port for query

### ISSUE THREAD

**Issue by josefig** [spc476/SPCDNS#11]
Hello Sean,

Thank you for publishing your code, it's been very useful for learning and personal projects. I have a doubt, I want to do query with your encode request, but this is a NAPTR type and the port is not the default port 53.

Is it possible for you to please indicate how can I do the query on a non-default port?

Thanks in advance!

**Comment by spc476** [comment]
The network code provided isn't meant to be used in production, but as a means to test the encoding and decoding of DNS packets.  As it states in the README file, it's simple and *dumb,* not something to be used in a real project (and perhaps I should clarify that point).
